version: "3"
services:
  notebook:
    # https://hub.docker.com/r/jupyter/datascience-notebookからimageをpullする
    image: jupyter/datascience-notebook
    # ポートの設定("ホスト：コンテナ")
    ports:
      - "8888:8888"
        # 環境変数の設定
    environment:
      - JUPYTER_ENABLE_LAB=yes
        # ボリューム(データの永続化の場所)の設定(ホスト:コンテナ)
        # ホスト内のworkディレクトリとコンテナ内の/home/jovyan/workディレクトリが紐づいているイメージ
    volumes:
      - /home/C0117035/hypergraph-clustering/:/home/jovyan/work
        # 最後にjupyterLabに接続するためのコマンドを実行する。
    command: start-notebook.sh --NotebookApp.token=''
